### ISSUE TITLE
This method not work

### ISSUE THREAD

**Issue by deletexl** [imvickykumar999/Download-Reels#1]
hello, I can't pull the data you show with this method, can you check if it works?

**Comment by deletexl** [comment]
{"message":"Please wait a few minutes before trying again.","require_login":true,"status":"fail"}

**Comment by imvickykumar999** [comment]
**Are you logged-in on Instagram** in the browser on which the flask server is running ?
Let me know and please reply.

Basically you have to append `?__a=1&__d=1` at end of profile or reel link (Note: underscore _ is 2 times __)

*like this...* (Open in new tab)
https://www.instagram.com/vix.bot/?__a=1&__d=1

and extract the video URL from the fetched dictionary.

In my case, everything is working well.

**Comment by anupamsoni200** [comment]
Same problem {"message":"Please wait a few minutes before you try again.","require_login":true,"status":"fail"}

**Comment by imvickykumar999** [comment]
> Same problem {"message":"Please wait a few minutes before you try again.","require_login":true,"status":"fail"}

Works for the local host in the Flask framework, but if you deploy then this error will be shown.

Try this in cmd

    >>> pip install DownloadReels
    >>> python
    >>> from DownloadReels import run_server

**Comment by imvickykumar999** [comment]
Explore this : https://github.com/subzeroid/instagrapi
